/**
 * Session event declaration-merge for the runtime-identity seam. The
 * three event types live here so the package is the single source of
 * truth for both the `SessionEventMap` augmentation and the host-side
 * producer calls; consumers that import from the package root receive
 * the merge through the type-only side effect of `index.ts`.
 *
 * All three events are first-party; the persistence read path treats
 * them as required-on-read in the same vocabulary as every other
 * repository-owned event (the
 * `KNOWN_SESSION_EVENT_TYPES` set is regenerated by
 * `scripts/gen-persistence-catalog.ts` and includes them automatically).
 *
 * @module @deepseek-ai/dsh-runtime-identity
 */

import type {
  RuntimeHeartbeatEvent,
  RuntimeHeartbeatLostEvent,
  RuntimeIdentityEvent,
} from './types.ts'

declare module '@deepseek-ai/dsh-session/types' {
  interface SessionEventMap {
    /**
     * The current runtime identity, committed at boot, on profile
     * switch, and on registry invalidation. Replayable; the latest
     * committed event is the canonical identity for any prefix.
     */
    'runtime/identity': RuntimeIdentityEvent
    /**
     * Periodic liveness marker. Persisted at the configured throttle
     * (turn/end + detach mandatory points + the interval's own
     * persistence schedule); `seq` is monotonic per host fiber. The
     * event is informational; the projection layer reads the latest
     * committed value to derive prompt-section freshness.
     */
    'runtime/heartbeat': RuntimeHeartbeatEvent
    /**
     * Committed when the heartbeat lapses: the registry did not observe
     * a fresh heartbeat within one interval plus configured grace. The
     * event is the first-class liveness signal a UI or a follow-up
     * session can subscribe to.
     */
    'runtime/heartbeat-lost': RuntimeHeartbeatLostEvent
  }
}
